[module]
[module.hugoVersion]
extended=true
[[module.mounts]]
source="assets/icons/bootstrap/_vendor"
target="assets/icons/bootstrap/vendor"
[[module.imports]]
path="github.com/twbs/icons"
[[module.imports.mounts]]
source="icons"
target="assets/icons/bootstrap"
[[module.imports.mounts]]
source="fonts"
target="assets/icons/bootstrap"

